### PR TITLE
OH2-220 | Add reset button in visit and laboratory filters

### PR DESCRIPTION
**Pull request by SteveGT96**
See OH2-220.

Also added the reset button in laboratory filter form.

### CODE REVIEW

**Comment by SteveGT96** [comment]
Hello @mwithi ! I've also added the reset button in laboratory filter form.

**Comment by SteveGT96** [comment]
Hello @mwithi ! I've also added the reset button in laboratory filter form.

**Review by mwithi — CHANGES_REQUESTED** [review]
Hello @SteveGT96 it seems that the two filter pages have different l&f: Visits has the filter button on the left, Laboratory on the right. I would make the same, and the RESET button always on the same side (on the left if FILTER is at right-end or viceversa).

Also looks like the two actions behave in different way (see OH2-220)

**Comment by mwithi** [comment]
Up!

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
