### PR TITLE
OH2-400 | OH2-403 Refactoring ResponseEntity

### PR DESCRIPTION
**Pull request by SilverD3**
See OH2-400 and OH2-403.

Alignement of changes brought by #[482](https://github.com/informatici/openhospital-api/pull/482)

### CODE REVIEW

**Review by SteveGT96 — APPROVED** [review]
LGTM

**Review by mwithi — DISMISSED** [review]
Reviewed and approved by @SteveGT96

**Comment by mwithi** [comment]
Don't know if it is related to API or UI. 

image

**Comment by SilverD3** [comment]
> Don't know if it is related to API or UI

https://github.com/informatici/openhospital-api/pull/498#issuecomment-2460261224

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
