### PR TITLE
OH2-193 | Display dashboard components base on user role/permission

### PR DESCRIPTION
**Pull request by SilverD3**
See OH2-193.

### Changes 
- Align APIs and Models with spec file.
- Update `TPermission` type
- Use Authenticated user permission to display dashboard widgets

### CODE REVIEW

**Comment by SilverD3** [comment]
The API `PUT /users/settings/{1}` used to update UserSetting is not working. That's why I marked this PR as draft.

**Comment by SilverD3** [comment]
Something like "A setting with the same name already exists"

**Comment by mwithi** [comment]
> Something like "A setting with the same name already exists"

pushed fix on api, please check, thanks

**Comment by SilverD3** [comment]
Looks good. 

I've test with the four users in the demo database.

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
