### PR TITLE
OH2-328 | Tests | Add cypress e2e tests to cover admin/operations

### PR DESCRIPTION
**Pull request by SilverD3**
See OH2-328

### CODE REVIEW

**Comment by mwithi** [comment]
hello @SilverD3, is this ready for review?

**Comment by SilverD3** [comment]
> hello @SilverD3, is this ready for review?

@mwithi yes

**Comment by mwithi** [comment]
> > hello @SilverD3, is this ready for review?
> 
> @mwithi yes

@[mwithi](https://github.com/mwithi) mwithi requested a review from [SteveGT96](https://github.com/SteveGT96) [3 weeks ago](https://github.com/informatici/openhospital-ui/pull/623#event-13317863439)

**Review by SteveGT96 — APPROVED** [review]

**Review by mwithi — APPROVED** [review]
Reviewed and approved by @SteveGT96

**Pull request merged**
