### PR TITLE
Op 187

### PR DESCRIPTION
**Pull request by aalsabag**
Changing to date field. The purpose of the shrink parameter is to prevent the overlay of the "birthdate" label on the "mm/dd/yyyy" making it unreadable

### CODE REVIEW

**Comment by mwithi** [comment]
Hi @aalsabag, welcome back :)

I think @almeida1492 will replace soon quite 80% of the code inside this repository, so this change would be rebased or even included di the next PR. Henrique what do you think?

**Comment by almeida1492** [comment]
> Hi @aalsabag, welcome back :)
> 
> I think @almeida1492 will replace soon quite 80% of the code inside this repository, so this change would be rebased or even included di the next PR. Henrique what do you think?

In the incoming changes, we are using sass for styling. Moreover, we have brand new input components that are still `material-ui`, but we are trying to standardize them.

**Comment by mwithi** [comment]
> In the incoming changes

Thanks @almeida1492, do you have any deadline?

**Comment by almeida1492** [comment]
I'm planning to do it this week. I'm just not sure what is the best approach for doing such a thing. The changes are too big.

**Comment by aalsabag** [comment]
Thanks for the heads up guys. I am anxious to see those changes 😉.
I'll take down the PR

**Comment by mwithi** [comment]
> The changes are too big.

I think we can just run the PR and review it, UI has never been distributed, so nobody will complain IMHO ;)

**Comment by mwithi** [comment]
superseded by https://github.com/informatici/openhospital-ui/pull/32

**Pull request closed without merging**
