### PR TITLE
OH2-401 | Fix admission state slice

### PR DESCRIPTION
**Pull request by SilverD3**
See OH2-401

Needs #670 to be merged

### CODE REVIEW

**Review by mwithi — CHANGES_REQUESTED** [review]
Integration test (real DB) fails:

image

Retry response:
```
{
    "type": "about:blank",
    "title": "Not Found",
    "status": 404,
    "detail": "No static resource users/admin/settings/dashboard.",
    "instance": "/users/admin/settings/dashboard"
}
```

Reset (no response):
image

Refresh (same as before):
image

**Comment by SilverD3** [comment]
I see, as [#465](https://github.com/informatici/openhospital-api/pull/463) has been merged, we need to align API specs in the FE.
I open an issue to align the FE

**Review by SteveGT96 — APPROVED** [review]

**Comment by SilverD3** [comment]
@mwithi please test again

**Comment by mwithi** [comment]
> @mwithi please test again

ok, now it's working, thanks!

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
