### PR TITLE
OHCS-62 | Navigate to home screen after login

### PR DESCRIPTION
**Pull request by SteveGT96**
Navigate to home screen after login when the user manually logged out previously

### CODE REVIEW

**Review by almeida1492 — CHANGES_REQUESTED** [review]
I think we are not resetting the state after the log-out yet. I mean, if I log in, search for a patient, log out and log in again, I see there are some remaining state values from the previous session. Perhaps that's what @mwithi was pointing out as an issue.

**Comment by mwithi** [comment]
> I think we are not resetting the state after the log-out yet. I mean, if I log in, search for a patient, log out and log in again, I see there are some remaining state values from the previous session. Perhaps that's what @mwithi was pointing out as an issue.

I didn't test yet the PR, but I guess the whole state should be reset. My initial test was just an example.

**Review by almeida1492 — CHANGES_REQUESTED** [review]
@SteveGT96 The state is not being reset yet. I see you declared an action creator named `resetAppState`, but you don't call it anywhere.

**Comment by SteveGT96** [comment]
> @SteveGT96 The state is not being reset yet. I see you declared an action creator named `resetAppState`, but you don't call it anywhere.

I forgot to apply it ! But I just did it right now.

**Review by almeida1492 — APPROVED** [review]

**Pull request merged**
