### PR TITLE
Fix/op 771 admissions section loading

### PR DESCRIPTION
**Pull request by nicolaburetta**
I added admission bookings and surgical records state management, although api have not yet been implemented. So an error will be printed in these sections.

### CODE REVIEW

**Comment by mwithi** [comment]
> although api have not yet been implemented.

@nicolaburetta is there any specification about the requested features?

**Comment by mwithi** [comment]
Up!

**Comment by nicolaburetta** [comment]
> > although api have not yet been implemented.
> 
> @nicolaburetta is there any specification about the requested features?

Honestly I don't know.
Which feature do you mean?
I'm working to the mock server

**Comment by nicolaburetta** [comment]
I can't see admission bookings within the api swagger.

**Pull request closed without merging**
