### PR TITLE
OH2-367 | Mock dashboard settings endpoint 

### PR DESCRIPTION
**Pull request by tedrosdev**
See issue  [OH2-367](https://openhospital.atlassian.net/browse/OH2-367). 

It ensures that the dashboard is visible and functional in the mock server.

[OH2-367]: https://openhospital.atlassian.net/browse/OH2-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gasp** [comment]
Congratulations for your first contribution to Open Hospital 🎉 

dashboard
It works well on my machine when using your branch

Thank you for the fix !

**Review by gasp — APPROVED** [review]

**Comment by tedrosdev** [comment]
Thank you! @gasp ,
 Glad to hear it works well on your machine. Looking forward to more contributions! 😊

**Review by SilverD3 — CHANGES_REQUESTED** [review]
Not working smoothly. Trying to remove a widget crashes the browser. Idem when we try to edit many widgets.

How to reproduce:

- Removing a widget: navigate to the dashboard page, try to remove a widget (page should crash)
- Editing many widgets: try to resize widget, change widgets order, repeat the process. From the second or third time the page crashes.

**Comment by mwithi** [comment]
> Not working smoothly. Trying to remove a widget crashes the browser. Idem when we try to edit many widgets.
> 
> How to reproduce:
> 
> * Removing a widget: navigate to the dashboard page, try to remove a widget (page should crash)
> * Editing many widgets: try to resize widget, change widgets order, repeat the process. From the second or third time the page crashes.

@Ted-AfroEm could you try to reproduce and fix these?

**Comment by gasp** [comment]
@mwithi @SilverD3 I am afraid those abovementioned bugs are related to the widget and not within the scope of this pull request.

This pull request should unlock testing and debugging the dashboard for multiple developers, I suggest we merge this code so that we can further code, debug and fix the dashboard!

**Comment by mwithi** [comment]
> @mwithi @SilverD3 I am afraid those abovementioned bugs are related to the widget and not within the scope of this pull request.
> 
> This pull request should unlock testing and debugging the dashboard for multiple developers, I suggest we merge this code so that we can further code, debug and fix the dashboard!

I agree that the scope of the current PR is to fix the mocked endpoint and this has been achieved so I'm going to merge it.
@SteveGT96 would you mind to create the new issues for the reproducible crashes?

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Comment by SteveGT96** [comment]
> > @mwithi @SilverD3 I am afraid those abovementioned bugs are related to the widget and not within the scope of this pull request.
> > This pull request should unlock testing and debugging the dashboard for multiple developers, I suggest we merge this code so that we can further code, debug and fix the dashboard!
> 
> I agree that the scope of the current PR is to fix the mocked endpoint and this has been achieved so I'm going to merge it. @SteveGT96 would you mind to create the new issues for the reproducible crashes?

Sure !

**Pull request merged**
