### PR TITLE
OH2-195 Store user dashboard preferences

### PR DESCRIPTION
**Pull request by SilverD3**
-See OH2-195.

Changes and additions : 

- I've integrated a new library, [`react-grid-layout`](https://github.com/react-grid-layout/react-grid-layout), which I've used to create a customizable dashboard (draggable and resizable). 
- Customization is saved using provided APIs. 
- Create a state to manage dashboard filter period

There are two known bugs as the moment:
- Dashboards inside widgets sometimes don't resize according to widgets size.
- On screen size change, in some cases, previous "screen size's customization" override current "screen size's customization".
As it could take some time (that I can't estimate for the moment) to fix those bugs (which are not crucial), I suggest to use the feature and in the meantime I will actively find a solution to fix those bugs.

### CODE REVIEW

**Comment by axelpezzo** [comment]
Hello @SilverD3, I would like to report some comments on this PR:
- I saw the reported bug on the resize issue, whats's wrong is on the react-grid-layout or on the widget itself? 
- I suggest to put the "available dashboards" on a modal which is triggered by a "settings icon" near the filter
- If it so, I suggest also to have a four full filled dashboard on a row and the others hidden and triggered only by the modal
- I saw that if I change the route (e.g. I go on Patient) after I add some dashabords from the setting menu, those dashboards are lost (they are not shown neither in the page and neither on the settings tab). The same happens for the filter which reset the values once I changed the route.
- Also the fullpage version I would enhance the UI, I would vertically center the dashboard and remove all the action button leaving only the resize icon (which should be different than the fullpage icon). Now in order to close the fullpage view, I click on X icon which remove the dashboard and this behaviour is not what I expect.
- Plus, the fullpage version I would add it only for the column bar graph leaving as is the pie chart.

**Comment by SilverD3** [comment]
Hello @axelpezzo !

Firstly, I made some changes. You can fetch updates from the same branch.

> I saw the reported bug on the resize issue, whats's wrong is on the react-grid-layout or on the widget itself?
The problem here concern the widget itself. I'm realizing that it's the CSS issue.

> I suggest to put the "available dashboards" on a modal which is triggered by a "settings icon" near the filter
Okay. I will think of it after fixing all bugs

> I saw that if I change the route (e.g. I go on Patient) after I add some dashabords from the setting menu, those dashboards are lost (they are not shown neither in the page and neither on the settings tab). The same happens for the filter which reset the values once I changed the route.
Fixed !

> Also the fullpage version I would enhance the UI, I would vertically center the dashboard and remove all the action button leaving only the resize icon (which should be different than the fullpage icon). Now in order to close the fullpage view, I click on X icon which remove the dashboard and this behaviour is not what I expect.
I updated the full screen mode.

> Plus, the fullpage version I would add it only for the column bar graph leaving as is the pie chart.
Okay. The full screen mode is optional anyway.

**Comment by SilverD3** [comment]
The most important bug for the moment concerns the library I used (react-grid-layout). In fact, when you change screen size (switch from desktop to tablet for example), previous layout config (desktop) overrides the current layout config (tablet) as I reported in this PR description (second bug).

**Comment by mwithi** [comment]
@SteveGT96 @axelpezzo how do we want to handle the two bugs? Are we going to merge this PR as is and open new issues for those bugs? Or you prefer to keep working on this PR? (I would prefer the first option)

**Comment by axelpezzo** [comment]
@SilverD3 let me know when this PR should be ready to be merged. If there still something to fix we're going to open a new issue.

**Comment by SilverD3** [comment]
@axelpezzo The PR is ready to be merged. I will continue working on bug fixes in parallel

**Comment by mwithi** [comment]
ok, please @SilverD3 could you resolve conflicts in package (I think after merge https://github.com/informatici/openhospital-ui/pull/473) so we can merge also this one? Thanks!

**Review by axelpezzo — APPROVED** [review]

**Comment by mwithi** [comment]
Hello @SilverD3, I've changed the linked issue to OP2-195 because I think it is the correct one realted to this PR.
It is still missing the API part (IN PROGRESS) as OH2-202, any news from Arnaud?

**Comment by SilverD3** [comment]
Hello @mwithi !
Okay for the linked issue. But the OH2-193 one will be implemented in another PR.
Arnaud said that he opened a PR for issue OH2-202.

I'm not able to re-run checks when they fail (for some reason not concerning the code, but GitHub's environment). So please re-run checks to make sure everything is okay.

**Comment by mwithi** [comment]
Hello @SilverD3, so the title was misguiding me... let me change it to "OH2-195 Store user dashboard preferences".

For the Arnaud part I don't see any PR on both [API](https://github.com/informatici/openhospital-api/pulls) and [CORE](https://github.com/informatici/openhospital-core/pulls). The PR should contain the issue code in the name, so they will also automatically linked to Jira.

I'v re-run checks and the error is this one:
```
npm ERR! Missing: react-draggable@4.4.5 from lock file
```

**Comment by axelpezzo** [comment]
@SilverD3 is this PR ready to be merged? If it so, please check the test which is failing.

**Comment by SilverD3** [comment]
Hello @axelpezzo  ! Yes the PR is ready for merge. The check failed due to GitHub's environment (i think). There's no problem with the code. Please re-run checks, I can only run checks by making a commit, but there's nothing to commit.

**Comment by mwithi** [comment]
The backend part has not been yet merged...

**Pull request merged**
