### PR TITLE
OH2-80 | Change flow for new patient

### PR DESCRIPTION
**Pull request by SteveGT96**

### CODE REVIEW

**Review by almeida1492 — CHANGES_REQUESTED** [review]
It looks like you forgot to apply the dialog component you wrote to the NewPatientActivity. When I submit the form, I still see the old confirmation dialog with just two buttons (keep editing and dashboard).

**Review by almeida1492 — CHANGES_REQUESTED** [review]
If I click on **PATIENT DASHBOARD** after submitting the new patient form, the app is redirected to `/patients` while it should be redirected to `patient/details`.

Moreover, I see some funny styling in the `/patients` view. Do you see that too?

Screenshot 2022-07-26 at 14 31 07

**Comment by SteveGT96** [comment]
> If I click on **PATIENT DASHBOARD** after submitting the new patient form, the app is redirected to `/patients` while it should be redirected to `patient/details`.
> 
> Moreover, I see some funny styling in the `/patients` view. Do you see that too?
> 
> Screenshot 2022-07-26 at 14 31 07

Hum sorry ! The devtools panel was opened and I did not notice that !

**Review by almeida1492 — CHANGES_REQUESTED** [review]
The styling problem was solved, but I still see the wrong navigation at the end of the form submission.

> If I click on PATIENT DASHBOARD after submitting the new patient form, the app is redirected to `/patients`while it should be redirected to `patients/details/#id`.

**Review by almeida1492 — CHANGES_REQUESTED** [review]
I was taking a look at the changes you introduced last and it looks like there's something still missing. If the user clicks on the button "PATIENT DASHBOARD", the app should redirect to `/patients/details/#id`, where `#id` is the id of the patient just created.

**Review by almeida1492 — APPROVED** [review]

**Pull request merged**
