### PR TITLE
OP-1043 | Remove deleted group from user edit group jcombo box

### PR DESCRIPTION
**Pull request by SteveGT96**
See [OP-1043](https://openhospital.atlassian.net/browse/OP-1043)

[OP-1043]: https://openhospital.atlassian.net/browse/OP-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mwithi** [comment]
Found that both User edit and Group edit do not have CANCEL option to go back without doing changes.
Moreover in User edit, in the column Groups, I wouls show the group name rather than its description, or both, by the moment that the column Deleted could be reduced in size.

Let me know if you want/could address these issues in this same PR or another issue (in which case we can merge this one).
Thanks

**Comment by SteveGT96** [comment]
> Found that both User edit and Group edit do not have CANCEL option to go back without doing changes. Moreover in User edit, in the column Groups, I wouls show the group name rather than its description, or both, by the moment that the column Deleted could be reduced in size.
> 
> Let me know if you want/could address these issues in this same PR or another issue (in which case we can merge this one). Thanks

Let's address that in a separate issue. Thanks.

**Comment by mwithi** [comment]
> Let's address that in a separate issue. Thanks.

Do you create the issue or I do?

**Comment by SteveGT96** [comment]
Please, do it !

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
