### PR TITLE
OH2-433 | Implement token refresh

### PR DESCRIPTION
**Pull request by SteveGT96**
See [OH2-433](https://openhospital.atlassian.net/browse/OH2-433)

[OH2-433]: https://openhospital.atlassian.net/browse/OH2-433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by SilverD3 — CHANGES_REQUESTED** [review]
Use `setInterval` to check every 5 seconds if the token has expired and refresh isn't the most efficient way to achieve token refresh. I would opt for checking the token expiration when a request is sent (if we received a 401, for example) and try to refresh the token.

With the current implementation, token and token refresh will never expired as long as the OH tab in the browser is open, even the user does nothing.

**Comment by mwithi** [comment]
Hi guys, ready to be merged? How can I test it?

**Review by SilverD3 — APPROVED** [review]
LGTM!

**Review by mwithi — APPROVED** [review]
Reviewed and approved by @SilverD3

**Pull request merged**
