### PR TITLE
OH2-430 - OH2-434 | Fix edit group component and update text field component

### PR DESCRIPTION
**Pull request by SteveGT96**
See [OH2-430](https://openhospital.atlassian.net/browse/OH2-430) and [OH2-434](https://openhospital.atlassian.net/browse/OH2-434).

[OH2-430]: https://openhospital.atlassian.net/browse/OH2-430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OH2-434]: https://openhospital.atlassian.net/browse/OH2-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mwithi — APPROVED** [review]
Better, although I think it could be further improved... @SilverD3 wdyt?

**Review by SilverD3 — COMMENTED** [review]
This PR only focuses on OH2-434, I think. I'm not seeing any changes that could improve (performance) user group edition

**Comment by mwithi** [comment]
> This PR only focuses on OH2-434, I think. I'm not seeing any changes that could improve (performance) user group edition

Isn't the fix for OH2-434 only the change on `src/components/accessories/textField/TextField.tsx` and the rest for OH2-430?

**Comment by SilverD3** [comment]
I know why user group edition is slow. I just don't know how to optimize yet. This PR doesn't get to the heart of the problem, but it's a start.

**Pull request merged**
