### PR TITLE
feat(oh2-299): new user form

### PR DESCRIPTION
**Pull request by gasp**
[OH2-299](https://openhospital.atlassian.net/browse/OH2-299)
newuser

[OH2-299]: https://openhospital.atlassian.net/browse/OH2-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by SteveGT96 — CHANGES_REQUESTED** [review]
Please, could you also add feedback dialog wether the operation succeeds or not ? (just like you've done for the Exam Form).

**Comment by gasp** [comment]
Thanks for the review, here is how it looks like.

created

**Comment by SilverD3** [comment]
LGTM!

In the [mock](https://w6nt6m.axshare.com/?code=373a8db2aee9ac436955a60fb179b091&id=kjyie9&p=add_user&g=1), we have `description` field, but I can see it in the form you provided.

**Comment by gasp** [comment]
Here is the user description, sorry for omitting the field!

Screen Recording 2024-07-15 at 15 13 47

**Review by SilverD3 — APPROVED** [review]
It's working and tests are passing!

**Comment by mwithi** [comment]
shouldn't the password be retyped twice?

**Comment by mwithi** [comment]
Also, the group field shows the groups' descriptions but not the groups' names

image

We could show them as "name - description" I guess...

image

**Comment by gasp** [comment]
> shouldn't the password be retyped twice?

Good idea, it shall reduce typing errors

**Comment by gasp** [comment]
> shouldn't the password be retyped twice?
> Also, the group field shows the groups' descriptions but not the groups' names
> We could show them as "name - description" I guess.

* Password should be retyped twice
* group selector now displays "code - description"

Screen Recording 2024-07-16 at 14 00 10

**Comment by gasp** [comment]
Small detail: autocomplete matches code or description
Screen Recording 2024-07-16 at 14 09 54

**Comment by mwithi** [comment]
User creation is ok. If User already exists the error message is not defined (we need to improve api though)

image

**Comment by mwithi** [comment]
I think that on the NEW USER page, we should also have a CANCEL button, and in case of error saving the USER (the message is ok now) it should not go back to the list but remain on the edit page

**Review by mwithi — APPROVED** [review]
Approved to move on with next developments

**Pull request merged**
