### PR TITLE
OH2-377 | Fix the dashboard

### PR DESCRIPTION
**Pull request by SilverD3**
See OH2-377

### CODE REVIEW

**Comment by mwithi** [comment]
Despite it loads the dashboard now (with demo data) I get the following errors:

image

with mocked data I still get:

image

**Comment by SilverD3** [comment]
> with mocked data I still get:

Normal! The issue [OH2-367](https://openhospital.atlassian.net/browse/OH2-367) will fix it

[OH2-367]: https://openhospital.atlassian.net/browse/OH2-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SilverD3** [comment]
> Despite it loads the dashboard now (with demo data) I get the following errors:

I'm not able to reproduce the issue
Open Hospital — Mozilla Firefox 2024-09-12 17-19-26

**Comment by mwithi** [comment]
> > Despite it loads the dashboard now (with demo data) I get the following errors:
> 
> I'm not able to reproduce the issue

Me too! Ok then...

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
