### PR TITLE
feat OH2-285: exams crud

### PR DESCRIPTION
**Pull request by gasp**
See OH2-285.

Admin/Exams CRUD

exams

### CODE REVIEW

**Review by SteveGT96 — CHANGES_REQUESTED** [review]
Thanks @gasp for the efforts.

I've noticed that the filter on the exam type field is not working, and the procedure field is not validated correctly. I can input 500 as value(I think procedures for the moment are 1, 2, 3. @mwithi could you confirm that ?).

**Comment by mwithi** [comment]
> Thanks @gasp for the efforts.
> 
> I've noticed that the filter on the exam type field is not working, and the procedure field is not validated correctly. I can input 500 as value(I think procedures for the moment are 1, 2, 3. @mwithi could you confirm that ?).

I confirm

**Comment by gasp** [comment]
Thanks for the feedback and the testing, I fixed those issues!

**Comment by SilverD3** [comment]
Wrong "save button"'s label
Screenshot 2024-07-15 at 08-50-19 Open Hospital

It should be "Save exam", I think.

Also `procedure` field should be same length as `code` field for suitable design

**Comment by gasp** [comment]
> Wrong "save button"'s label
> Screenshot 2024-07-15 at 08-50-19 Open Hospital
> 
> It should be "Save exam", I think.
> 
> Also `procedure` field should be same length as `code` field for suitable design

Ha ha, I copypasted 😅
Thanks for the feedback!

**Comment by gasp** [comment]
Fixed, thanks @SilverD3 

Screenshot 2024-07-15 at 15 23 35

**Review by SilverD3 — APPROVED** [review]

**Comment by mwithi** [comment]
Procedure 1, 2 or 3 imply that, aside the default value, one should also define other sets of data:

- Procedure 1: a list of available "string" results
- Procedure 2: a list of all "boolean" results
- Proceudre 3: exact value (it will be typed in by the laboratorist)

For this reason I would change Procedure field to a selector in first sight.
Please have a look at how the feature is working in the GUI.

image

**Procedure 1**:

image

**Procedure 2**:

image

**Procedure 3** (no predefined results):

image

**Comment by mwithi** [comment]
Also, I get this error on saving with real backend:

image

**Comment by gasp** [comment]
> Also, I get this error on saving with real backend:

My bad, backend expects an `examtype`, not a `type`. It's fixed now!

Screenshot 2024-07-16 at 14 23 33


What does the "lock" property stand for?

**Comment by mwithi** [comment]
> What does the "lock" property stand for?

is for record versioning, you should read from the DB and send back: if it is changed the update will be refused for concurring access

**Review by SteveGT96 — APPROVED** [review]

**Review by SteveGT96 — CHANGES_REQUESTED** [review]
Hi @gasp. Please, fix the pipeline and then we could move on.

**Comment by gasp** [comment]
> Hi @gasp. Please, fix the pipeline and then we could move on.

should I fix https://github.com/informatici/openhospital-ui/pull/601#issuecomment-2230318803 in a separate pull request then ?

**Comment by SteveGT96** [comment]
> > Hi @gasp. Please, fix the pipeline and then we could move on.
> 
> should I fix [#601 (comment)](https://github.com/informatici/openhospital-ui/pull/601#issuecomment-2230318803) in a separate pull request then ?

Sorry, I did not see it early. You could fix it here before we move on.

**Comment by gasp** [comment]
Screenshot from 2024-07-24 19-45-59

Changed procedure to be a select

**Comment by gasp** [comment]
@mwithi @SteveGT96 , As I am coding the changes, I realize that we can't edit `examRows` without having an exam, so I would not recommend having both in the same form (such as in the GUI view).

Thus, that handling the `examRows` is not a trivial change and involves design decisions. I would recommend reviewing it separately. Can we merge this PR for clarity?

**Comment by mwithi** [comment]
> @mwithi @SteveGT96 , As I am coding the changes, I realize that we can't edit `examRows` without having an exam, so I would not recommend having both in the same form (such as in the GUI view).
> 
> Thus, that handling the `examRows` is not a trivial change and involves design decisions. I would recommend reviewing it separately. Can we merge this PR for clarity?

I think we should have an ExamDTO including its ExamRowDTOs and to send it as is to API for persistance. @SilverD3 don't you mind to create an issue for this?

@gasp let's merge this one and then we'll see how to move on.

**Review by mwithi — APPROVED** [review]
Approve temporary work in order to better design the model

**Pull request merged**
