### PR TITLE
feature(patient router tabs):[OP-480] - implemented patient router tabs navigation

### PR DESCRIPTION
**Pull request by elvisciuffetelli**
[OP-480] - implemented patient router tabs navigation

[OP-480]: https://openhospital.atlassian.net/browse/OP-480

### CODE REVIEW

**Review by axelpezzo — APPROVED** [review]

**Comment by alefalezza** [comment]
We should support page refresh. Now if you refresh the page on a subroute, you are redirected to summary.
Redirection could be removed with ease (it's in a useEffect), but then you have to handle active menu item.

**Comment by elvisciuffetelli** [comment]
> We should support page refresh. Now if you refresh the page on a subroute, you are redirected to summary.
> Redirection could be removed with ease (it's in a useEffect), but then you have to handle active menu item.

The problem in removing the Summary route history push from the useEffect is that we need a default one. Maybe a solution can be to save the current route in the session storage and then recover it from there after reloading the page?

**Comment by alefalezza** [comment]
> > We should support page refresh. Now if you refresh the page on a subroute, you are redirected to summary.
> > Redirection could be removed with ease (it's in a useEffect), but then you have to handle active menu item.
> 
> The problem in removing the Summary route history push from the useEffect is that we need a default one. Maybe a solution can be to save the current route in the session storage and then recover it from there after reloading the page?

I think it would be better to use current location to select active tab, it also supports deep linking, which is nice.
I think "currentIndex" could be string (`url + item.path`) instead of number, and current tab should match current location.

Even better, match could be evaluated with a regexp like `/^(location_here)([\/?].*)?$/`, which matches:
- "location"
-  "location/"
-  "location/sub"
-  "location?query" 

but not:
- "location/sub1"
- "location/sub1/"
- "location/sub1?query"

**Comment by alefalezza** [comment]
> > > We should support page refresh. Now if you refresh the page on a subroute, you are redirected to summary.
> > > Redirection could be removed with ease (it's in a useEffect), but then you have to handle active menu item.
> > 
> > 
> > The problem in removing the Summary route history push from the useEffect is that we need a default one. Maybe a solution can be to save the current route in the session storage and then recover it from there after reloading the page?
> 
> I think it would be better to use current location to select active tab, it also supports deep linking, which is nice.
> I think "currentIndex" could be string (`url + item.path`) instead of number, and current tab should match current location.
> 
> Even better, match could be evaluated with a regexp like `/^(location_here)([\/?].*)?$/`, which matches:
> 
> * "location"
> * "location/"
> * "location/sub"
> * "location?query"
> 
> but not:
> 
> * "location/sub1"
> * "location/sub1/"
> * "location/sub1?query"

I think current path could be evaluated as:

```typescript
const {pathname} = useLocation();
const currentPath: string | undefined = config.map(item => item.path).find(path => pathname.match(new RegExp(`^(${url}${path})([/?].*)?$`, "gi")));
```

**Comment by elvisciuffetelli** [comment]
@alefalezza I understand regarding the active tab. But what about the first route pushed to the history when we land on the page? If we remove this useEffect:
` useEffect(() => {
    // default tab route - summary
    history.push(`${url}/summary`)
  }, [history, url]);`

there won't be any tab route pushed to the history, so no tab will be rendered until the user click on a tab

**Comment by alefalezza** [comment]
> @alefalezza I understand regarding the active tab. But what about the first route pushed to the history when we land on the page? If we remove this useEffect:
> 
> ```js
>  useEffect(() => {
>     // default tab route - summary
>     history.push(`${url}/summary`)
>   }, [history, url]);
> ```
> 
> there won't be any tab route pushed to the history, so no tab will be rendered until the user click on a tab

I suggest you:

- to parametrize `/summary` using an optional prop, so it can be injected and RouterTabs reusability increases
- to handle default route adding a check on currentRoute, and going to default only if current tab is undefined AND default route is defined (that's why it's an optional prop)

**Comment by elvisciuffetelli** [comment]
Ok got it, now it supports page refresh  👍

**Comment by alefalezza** [comment]
Perfect, thank you @elvisciuffetelli !

**Pull request merged**
