### PR TITLE
fix(wording): patient edit submit is a save action

### PR DESCRIPTION
**Pull request by gasp**
This is actually a "save" action, not a send action

how it looks like after the change:

Screenshot from 2024-02-21 12-12-50
Screenshot from 2024-02-21 12-13-04

### CODE REVIEW

**Comment by gasp** [comment]
This PR requires #572 to be merged

**Comment by mwithi** [comment]
> This PR requires #572 to be merged

#572 is merged, should be this PR ready for review now?

**Comment by gasp** [comment]
Soon, I'll rebase, apply the necessary changes and do some testing first

**Comment by gasp** [comment]
Now it's waiting for https://github.com/informatici/openhospital-ui/pull/574 to be merged

**Review by axelpezzo — APPROVED** [review]

**Pull request merged**
