### PR TITLE
components  / Ward: fix broken component

### PR DESCRIPTION
**Pull request by AceGentile**
Ward component is broken, fix explosions

### CODE REVIEW

**Comment by almeida1492** [comment]
@AceGentile @xrmx I think it's better if we work on branches from the main repo. I wanted to take a look at these files and I realized it was a fork. So, every time I want to check something out in a wider context, I'll have to clone the forks of who's asking for a review. What do you guys say about it?

**Comment by mwithi** [comment]
@almeida1492 you don't need to fork their work but just to follow the command line instructions on the pull-request itself
image

**Comment by xrmx** [comment]
ping?

**Comment by almeida1492** [comment]
go, go, go

**Pull request merged**
