### PR TITLE
OH2-228 | Add hospital info on print

### PR DESCRIPTION
**Pull request by SteveGT96**
See OH2-228.

This add the hospital info on the top of some pages when printing.

For the moment, Hospital infos have been added on the top of pages located in the activities PatientDetails, Laboratory, Visit. 
They could be added in other pages if necessary, using the HospitalInfo component.

### CODE REVIEW

**Comment by mwithi** [comment]
I think header is ok (we should think about how to change the logo though)

image

pay attention that long notes are not wrapped and scrollbars should be avoided, as well as untranslated labels (see angal.lab.blood.txt)

image

Also, seems there are conflicts with src/styles/index.scss

**Comment by SteveGT96** [comment]
Hello @mwithi ! For labels translation, I think we'll need a standard to manage internationalized fields. For the unwrapped content, I'm not able to reproduce it.

**Comment by mwithi** [comment]
> Hello @mwithi ! For labels translation, I think we'll need a standard to manage internationalized fields. For the unwrapped content, I'm not able to reproduce it.

The LabManager in core returns an HashMap with "keys" -> translations, you can you use those "keys" as any other language key for UI translations.
Anyway, the material can be hidden in the UI, and so its translations, see https://openhospital.atlassian.net/browse/OHCS-73

**Comment by SteveGT96** [comment]
> > Hello @mwithi ! For labels translation, I think we'll need a standard to manage internationalized fields. For the unwrapped content, I'm not able to reproduce it.
> 
> The LabManager in core returns an HashMap with "keys" -> translations, you can you use those "keys" as any other language key for UI translations. Anyway, the material can be hidden in the UI, and so its translations, see https://openhospital.atlassian.net/browse/OHCS-73

Is there yet an endpoint that serves those translations ?

**Comment by mwithi** [comment]
> Is there yet an endpoint that serves those translations ?

`/laboratories/materials`

**Comment by SteveGT96** [comment]
OK ! I think if there is not matter with the Hospital Header  info then we could merge this PR and then create issues for extra minor bugs.

**Comment by mwithi** [comment]
> OK ! I think if there is not matter with the Hospital Header info then we could merge this PR and then create issues for extra minor bugs.

Ok, but the issue for the material is already in progress (to hide them), I will open the one for the hospital logo

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Comment by SteveGT96** [comment]
> > OK ! I think if there is not matter with the Hospital Header info then we could merge this PR and then create issues for extra minor bugs.
> 
> Ok, but the issue for the material is already in progress (to hide them), I will open the one for the hospital logo

@SilverD3 is working on it !

**Pull request merged**
